// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: appointments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAppointmentsByDoctorAndStatus = `-- name: CountAppointmentsByDoctorAndStatus :one
SELECT COUNT(*) FROM appointments
WHERE doctor_id = $1 AND status = $2
`

type CountAppointmentsByDoctorAndStatusParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Status   string    `json:"status"`
}

func (q *Queries) CountAppointmentsByDoctorAndStatus(ctx context.Context, arg CountAppointmentsByDoctorAndStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppointmentsByDoctorAndStatus, arg.DoctorID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
  patient_id,
  doctor_id,
  application_id,
  time_of_appointment,
  status,
  description,
  appointment_results
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results
`

type CreateAppointmentParams struct {
	PatientID          uuid.UUID `json:"patient_id"`
	DoctorID           uuid.UUID `json:"doctor_id"`
	ApplicationID      uuid.UUID `json:"application_id"`
	TimeOfAppointment  time.Time `json:"time_of_appointment"`
	Status             string    `json:"status"`
	Description        string    `json:"description"`
	AppointmentResults string    `json:"appointment_results"`
}

// EXISTING QUERIES CONTINUE BELOW
func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, createAppointment,
		arg.PatientID,
		arg.DoctorID,
		arg.ApplicationID,
		arg.TimeOfAppointment,
		arg.Status,
		arg.Description,
		arg.AppointmentResults,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ApplicationID,
		&i.TimeOfAppointment,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppointmentResults,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments
WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAppointment, id)
	return err
}

const getAppointment = `-- name: GetAppointment :one
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppointment(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ApplicationID,
		&i.TimeOfAppointment,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppointmentResults,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
ORDER BY time_of_appointment ASC
LIMIT $1 OFFSET $2
`

type ListAppointmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ApplicationID,
			&i.TimeOfAppointment,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByDoctor = `-- name: ListAppointmentsByDoctor :many
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
WHERE doctor_id = $1
ORDER BY time_of_appointment ASC
LIMIT $2 OFFSET $3
`

type ListAppointmentsByDoctorParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAppointmentsByDoctor(ctx context.Context, arg ListAppointmentsByDoctorParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByDoctor, arg.DoctorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ApplicationID,
			&i.TimeOfAppointment,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByPatient = `-- name: ListAppointmentsByPatient :many
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
WHERE patient_id = $1
ORDER BY time_of_appointment ASC
LIMIT $2 OFFSET $3
`

type ListAppointmentsByPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListAppointmentsByPatient(ctx context.Context, arg ListAppointmentsByPatientParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ApplicationID,
			&i.TimeOfAppointment,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByStatus = `-- name: ListAppointmentsByStatus :many
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
WHERE status = $1
ORDER BY time_of_appointment ASC
LIMIT $2 OFFSET $3
`

type ListAppointmentsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListAppointmentsByStatus(ctx context.Context, arg ListAppointmentsByStatusParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ApplicationID,
			&i.TimeOfAppointment,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctorAppointmentsStats = `-- name: ListDoctorAppointmentsStats :one
SELECT 
  COUNT(*) FILTER (WHERE status = 'scheduled') as scheduled_count,
  COUNT(*) FILTER (WHERE status = 'completed') as completed_count,
  COUNT(*) FILTER (WHERE status = 'cancelled') as cancelled_count,
  COUNT(*) FILTER (WHERE date(time_of_appointment) = CURRENT_DATE) as today_count
FROM appointments
WHERE doctor_id = $1
`

type ListDoctorAppointmentsStatsRow struct {
	ScheduledCount int64 `json:"scheduled_count"`
	CompletedCount int64 `json:"completed_count"`
	CancelledCount int64 `json:"cancelled_count"`
	TodayCount     int64 `json:"today_count"`
}

func (q *Queries) ListDoctorAppointmentsStats(ctx context.Context, doctorID uuid.UUID) (ListDoctorAppointmentsStatsRow, error) {
	row := q.db.QueryRowContext(ctx, listDoctorAppointmentsStats, doctorID)
	var i ListDoctorAppointmentsStatsRow
	err := row.Scan(
		&i.ScheduledCount,
		&i.CompletedCount,
		&i.CancelledCount,
		&i.TodayCount,
	)
	return i, err
}

const listTodayAppointmentsByDoctor = `-- name: ListTodayAppointmentsByDoctor :many
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
WHERE doctor_id = $1 
  AND date(time_of_appointment) = CURRENT_DATE
ORDER BY time_of_appointment ASC
LIMIT $2 OFFSET $3
`

type ListTodayAppointmentsByDoctorParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

// NEW QUERIES FOR DOCTOR DASHBOARD
func (q *Queries) ListTodayAppointmentsByDoctor(ctx context.Context, arg ListTodayAppointmentsByDoctorParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listTodayAppointmentsByDoctor, arg.DoctorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ApplicationID,
			&i.TimeOfAppointment,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointments = `-- name: ListUpcomingAppointments :many
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
WHERE time_of_appointment > NOW()
ORDER BY time_of_appointment ASC
LIMIT $1 OFFSET $2
`

type ListUpcomingAppointmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUpcomingAppointments(ctx context.Context, arg ListUpcomingAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingAppointments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ApplicationID,
			&i.TimeOfAppointment,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointmentsByDoctor = `-- name: ListUpcomingAppointmentsByDoctor :many
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
WHERE doctor_id = $1 AND time_of_appointment > NOW()
ORDER BY time_of_appointment ASC
LIMIT $2 OFFSET $3
`

type ListUpcomingAppointmentsByDoctorParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListUpcomingAppointmentsByDoctor(ctx context.Context, arg ListUpcomingAppointmentsByDoctorParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingAppointmentsByDoctor, arg.DoctorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ApplicationID,
			&i.TimeOfAppointment,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointmentsByPatient = `-- name: ListUpcomingAppointmentsByPatient :many
SELECT id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results FROM appointments
WHERE patient_id = $1 AND time_of_appointment > NOW()
ORDER BY time_of_appointment ASC
LIMIT $2 OFFSET $3
`

type ListUpcomingAppointmentsByPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListUpcomingAppointmentsByPatient(ctx context.Context, arg ListUpcomingAppointmentsByPatientParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingAppointmentsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.ApplicationID,
			&i.TimeOfAppointment,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments
SET 
  time_of_appointment = $2,
  status = $3,
  appointment_results = $4,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results
`

type UpdateAppointmentParams struct {
	ID                 uuid.UUID `json:"id"`
	TimeOfAppointment  time.Time `json:"time_of_appointment"`
	Status             string    `json:"status"`
	AppointmentResults string    `json:"appointment_results"`
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointment,
		arg.ID,
		arg.TimeOfAppointment,
		arg.Status,
		arg.AppointmentResults,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ApplicationID,
		&i.TimeOfAppointment,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppointmentResults,
	)
	return i, err
}

const updateAppointmentResults = `-- name: UpdateAppointmentResults :one
UPDATE appointments
SET 
  appointment_results = $2,
  status = 'completed',
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results
`

type UpdateAppointmentResultsParams struct {
	ID                 uuid.UUID `json:"id"`
	AppointmentResults string    `json:"appointment_results"`
}

func (q *Queries) UpdateAppointmentResults(ctx context.Context, arg UpdateAppointmentResultsParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointmentResults, arg.ID, arg.AppointmentResults)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ApplicationID,
		&i.TimeOfAppointment,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppointmentResults,
	)
	return i, err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET 
  status = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, patient_id, doctor_id, application_id, time_of_appointment, status, description, created_at, updated_at, appointment_results
`

type UpdateAppointmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointmentStatus, arg.ID, arg.Status)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.ApplicationID,
		&i.TimeOfAppointment,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppointmentResults,
	)
	return i, err
}
