// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: doctors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDoctor = `-- name: CreateDoctor :one
INSERT INTO doctors (
  username,
  first_name,
  last_name,
  email,
  password_hash,
  specialization,
  salt
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, username, first_name, last_name, email, password_hash, specialization, salt, created_at, updated_at
`

type CreateDoctorParams struct {
	Username       string `json:"username"`
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	Email          string `json:"email"`
	PasswordHash   string `json:"password_hash"`
	Specialization string `json:"specialization"`
	Salt           string `json:"salt"`
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, createDoctor,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Specialization,
		arg.Salt,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Specialization,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDoctor = `-- name: DeleteDoctor :exec
DELETE FROM doctors
WHERE id = $1
`

func (q *Queries) DeleteDoctor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDoctor, id)
	return err
}

const getDoctor = `-- name: GetDoctor :one
SELECT id, username, first_name, last_name, email, password_hash, specialization, salt, created_at, updated_at FROM doctors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDoctor(ctx context.Context, id uuid.UUID) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, getDoctor, id)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Specialization,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctorByEmail = `-- name: GetDoctorByEmail :one
SELECT id, username, first_name, last_name, email, password_hash, specialization, salt, created_at, updated_at FROM doctors
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetDoctorByEmail(ctx context.Context, email string) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, getDoctorByEmail, email)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Specialization,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctorByUsername = `-- name: GetDoctorByUsername :one
SELECT id, username, first_name, last_name, email, password_hash, specialization, salt, created_at, updated_at FROM doctors
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetDoctorByUsername(ctx context.Context, username string) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, getDoctorByUsername, username)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Specialization,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDoctors = `-- name: ListDoctors :many
SELECT id, username, first_name, last_name, email, password_hash, specialization, salt, created_at, updated_at FROM doctors
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDoctorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDoctors(ctx context.Context, arg ListDoctorsParams) ([]Doctor, error) {
	rows, err := q.db.QueryContext(ctx, listDoctors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doctor
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Specialization,
			&i.Salt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctorsBySpecialization = `-- name: ListDoctorsBySpecialization :many
SELECT id, username, first_name, last_name, email, password_hash, specialization, salt, created_at, updated_at FROM doctors
WHERE specialization = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDoctorsBySpecializationParams struct {
	Specialization string `json:"specialization"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListDoctorsBySpecialization(ctx context.Context, arg ListDoctorsBySpecializationParams) ([]Doctor, error) {
	rows, err := q.db.QueryContext(ctx, listDoctorsBySpecialization, arg.Specialization, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doctor
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Specialization,
			&i.Salt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoctor = `-- name: UpdateDoctor :one
UPDATE doctors
SET 
  username = COALESCE($2, username),
  email = COALESCE($3, email),
  password_hash = COALESCE($4, password_hash),
  specialization = COALESCE($5, specialization),
  salt = COALESCE($6, salt),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, first_name, last_name, email, password_hash, specialization, salt, created_at, updated_at
`

type UpdateDoctorParams struct {
	ID             uuid.UUID `json:"id"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	PasswordHash   string    `json:"password_hash"`
	Specialization string    `json:"specialization"`
	Salt           string    `json:"salt"`
}

func (q *Queries) UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, updateDoctor,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Specialization,
		arg.Salt,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Specialization,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
