// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
  username,
  first_name,
  last_name,
  email,
  password_hash,
  salt,
  phone
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, username, first_name, last_name, email, password_hash, salt, phone, created_at, updated_at
`

type CreatePatientParams struct {
	Username     string `json:"username"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Salt         string `json:"salt"`
	Phone        string `json:"phone"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRowContext(ctx, createPatient,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Salt,
		arg.Phone,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients
WHERE id = $1
`

func (q *Queries) DeletePatient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePatient, id)
	return err
}

const getPatient = `-- name: GetPatient :one
SELECT id, username, first_name, last_name, email, password_hash, salt, phone, created_at, updated_at FROM patients
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPatient(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatient, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByEmail = `-- name: GetPatientByEmail :one
SELECT id, username, first_name, last_name, email, password_hash, salt, phone, created_at, updated_at FROM patients
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetPatientByEmail(ctx context.Context, email string) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByEmail, email)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByPhone = `-- name: GetPatientByPhone :one
SELECT id, username, first_name, last_name, email, password_hash, salt, phone, created_at, updated_at FROM patients
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetPatientByPhone(ctx context.Context, phone string) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByPhone, phone)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByUsername = `-- name: GetPatientByUsername :one
SELECT id, username, first_name, last_name, email, password_hash, salt, phone, created_at, updated_at FROM patients
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetPatientByUsername(ctx context.Context, username string) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByUsername, username)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, username, first_name, last_name, email, password_hash, salt, phone, created_at, updated_at FROM patients
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPatientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error) {
	rows, err := q.db.QueryContext(ctx, listPatients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Salt,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET 
  first_name = COALESCE($2, first_name),
  last_name = COALESCE($3, last_name),
  email = COALESCE($4, email),
  password_hash = COALESCE($5, password_hash),
  salt = COALESCE($6, salt),
  phone = COALESCE($7, phone),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, first_name, last_name, email, password_hash, salt, phone, created_at, updated_at
`

type UpdatePatientParams struct {
	ID           uuid.UUID `json:"id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Salt         string    `json:"salt"`
	Phone        string    `json:"phone"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRowContext(ctx, updatePatient,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Salt,
		arg.Phone,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
