// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: receptionists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createReceptionist = `-- name: CreateReceptionist :one
INSERT INTO receptionists (
  username,
  first_name,
  last_name,
  email,
  password_hash,
  salt
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, username, first_name, last_name, email, password_hash, salt, created_at, updated_at
`

type CreateReceptionistParams struct {
	Username     string `json:"username"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Salt         string `json:"salt"`
}

func (q *Queries) CreateReceptionist(ctx context.Context, arg CreateReceptionistParams) (Receptionist, error) {
	row := q.db.QueryRowContext(ctx, createReceptionist,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Salt,
	)
	var i Receptionist
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReceptionist = `-- name: DeleteReceptionist :exec
DELETE FROM receptionists
WHERE id = $1
`

func (q *Queries) DeleteReceptionist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReceptionist, id)
	return err
}

const getReceptionist = `-- name: GetReceptionist :one
SELECT id, username, first_name, last_name, email, password_hash, salt, created_at, updated_at FROM receptionists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReceptionist(ctx context.Context, id uuid.UUID) (Receptionist, error) {
	row := q.db.QueryRowContext(ctx, getReceptionist, id)
	var i Receptionist
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReceptionistByEmail = `-- name: GetReceptionistByEmail :one
SELECT id, username, first_name, last_name, email, password_hash, salt, created_at, updated_at FROM receptionists
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetReceptionistByEmail(ctx context.Context, email string) (Receptionist, error) {
	row := q.db.QueryRowContext(ctx, getReceptionistByEmail, email)
	var i Receptionist
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReceptionistByUsername = `-- name: GetReceptionistByUsername :one
SELECT id, username, first_name, last_name, email, password_hash, salt, created_at, updated_at FROM receptionists
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetReceptionistByUsername(ctx context.Context, username string) (Receptionist, error) {
	row := q.db.QueryRowContext(ctx, getReceptionistByUsername, username)
	var i Receptionist
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReceptionists = `-- name: ListReceptionists :many
SELECT id, username, first_name, last_name, email, password_hash, salt, created_at, updated_at FROM receptionists
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListReceptionistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReceptionists(ctx context.Context, arg ListReceptionistsParams) ([]Receptionist, error) {
	rows, err := q.db.QueryContext(ctx, listReceptionists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receptionist
	for rows.Next() {
		var i Receptionist
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Salt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReceptionist = `-- name: UpdateReceptionist :one
UPDATE receptionists
SET 
  username = COALESCE($2, username),
  email = COALESCE($3, email),
  password_hash = COALESCE($4, password_hash),
  salt = COALESCE($5, salt),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, first_name, last_name, email, password_hash, salt, created_at, updated_at
`

type UpdateReceptionistParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Salt         string    `json:"salt"`
}

func (q *Queries) UpdateReceptionist(ctx context.Context, arg UpdateReceptionistParams) (Receptionist, error) {
	row := q.db.QueryRowContext(ctx, updateReceptionist,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Salt,
	)
	var i Receptionist
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
