// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package sqlc

import (
	"context"
)

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, email, password_hash, salt, created_at, updated_at FROM admins
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
