// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: applications.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
  patient_id,
  doctor_id,
  status,
  description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, patient_id, doctor_id, status, description, created_at, updated_at
`

type CreateApplicationParams struct {
	PatientID   uuid.UUID      `json:"patient_id"`
	DoctorID    uuid.UUID      `json:"doctor_id"`
	Status      string         `json:"status"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.PatientID,
		arg.DoctorID,
		arg.Status,
		arg.Description,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, patient_id, doctor_id, status, description, created_at, updated_at FROM applications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT id, patient_id, doctor_id, status, description, created_at, updated_at FROM applications
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListApplicationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListApplications(ctx context.Context, arg ListApplicationsParams) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listApplications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByDoctor = `-- name: ListApplicationsByDoctor :many
SELECT id, patient_id, doctor_id, status, description, created_at, updated_at FROM applications
WHERE doctor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApplicationsByDoctorParams struct {
	DoctorID uuid.UUID `json:"doctor_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListApplicationsByDoctor(ctx context.Context, arg ListApplicationsByDoctorParams) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationsByDoctor, arg.DoctorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByPatient = `-- name: ListApplicationsByPatient :many
SELECT id, patient_id, doctor_id, status, description, created_at, updated_at FROM applications
WHERE patient_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApplicationsByPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListApplicationsByPatient(ctx context.Context, arg ListApplicationsByPatientParams) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByStatus = `-- name: ListApplicationsByStatus :many
SELECT id, patient_id, doctor_id, status, description, created_at, updated_at FROM applications
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApplicationsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListApplicationsByStatus(ctx context.Context, arg ListApplicationsByStatusParams) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.DoctorID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET 
  patient_id = COALESCE($2, patient_id),
  doctor_id = COALESCE($3, doctor_id),
  status = COALESCE($4, status),
  description = COALESCE($5, description),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, patient_id, doctor_id, status, description, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID          uuid.UUID      `json:"id"`
	PatientID   uuid.UUID      `json:"patient_id"`
	DoctorID    uuid.UUID      `json:"doctor_id"`
	Status      string         `json:"status"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplication,
		arg.ID,
		arg.PatientID,
		arg.DoctorID,
		arg.Status,
		arg.Description,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET 
  status = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, patient_id, doctor_id, status, description, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationStatus, arg.ID, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.DoctorID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
